### PR TITLE
Deal with DateTime timezones specified as offsets, not names

### LINKED ISSUE #2: dates with timezones specified as offsets cause IntlDateFormatter construct exception
This is an edge case, but if your environment uses UTC offsets rather than named timezones:

```
$time = new \DateTime('2019-01-01')
$time->setTimezone(new \DateTimeZone('-0400'));
```

and then pass this into Ranger, you'll get this error:

```
IntlException: datefmt_create: no such time zone: '-0400': U_ILLEGAL_ARGUMENT_ERROR
```

Luckily there's an easy fix: initialize `IntlDateFormatter` with the DateTimeZone object, rather than the name (see "timezone" parameter on http://php.net/manual/en/intldateformatter.create.php)

PR incoming.

### PR DESCRIPTION
**Pull request by ahebrank**
Fixes #2

### CODE REVIEW

**Comment by flack** [comment]
@ahebrank I just ran a simplified version of your testcase on a PHP 5.6 machine:

```php
date_default_timezone_set('UTC');
$start = new DateTime('2013-10-05');
$tz = new \DateTimeZone('-0500');
$start->setTimezone($tz);
echo $start->format('Y-m-d H:i:s');
// outputs: 2013-10-04 19:00:00
```

So it looks like it's working fine in this version (and it'll probably be ok in 5.5, too), at least with the native `php-intl` extension. I'm not sure, but maybe Travis runs with the Symfony fallback, and they don't support offsets in those versions at least? 

If that is the case, we could simply skip the test for the affected PHP versions if the extension is not found. And for PHP 5.4. like I wrote in the ticket, we can just drop support (i.e. remove 5.4 from .travis.yml and bump to 5.5 in `composer.json`)

**Comment by flack** [comment]
P.S.: Do you think you could get rid of the merge commit? Because the PR contains three commits, but only the last one is the actual change

**Comment by ahebrank** [comment]
Yeah, let me see if I can patch from a clean history.

**Comment by flack** [comment]
Thanks for the PR, looks good! I think we can probably change the test logic to only skip if the `intl` extension is not installed, but that can be done in a followup commit

**Pull request merged**
